spring:
  application:
    name: koslink
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgresql.database.svc.cluster.local:5432/koscomdb}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:adminpassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

naver:
  api:
    client-id: ${NAVER_CLIENT_ID:XDfkw7nEXh_TSWWWbYBy}
    client-secret: ${NAVER_CLIENT_SECRET:A6wJY6CriE}
    base-url: ${NAVER_BASE_URL:https://openapi.naver.com}
    news-search-path: /v1/search/news.json

crawler:
  delay-ms: 200  # 크롤링 요청 간 최소 딜레이 (밀리초)

news:
  analyze:
    base-url: ${NEWS_ANALYZE_BASE_URL:http://koslink-ai-app:8000}
